sulon_security:
    resource: "@SulonSecurityBundle/Resources/config/routing.yml"
    prefix:   /

sulon_user:
    resource: "@SulonUserBundle/Resources/config/routing.yml"
    prefix:   /

sulon_app:
    resource: "@SulonAppBundle/Resources/config/routing.yml"
    prefix:   /
